version: "3"

services:
  web:
    build: .
    restart: always
    command: npm start
    volumes:
      - './:/poupa-up'
    ports:
      - "7777:7777"
    environment:
      NODE_ENV: "development"