version: "3"

services:
  web:
    build: .
    restart: always
    command: npm start
    env_file:
      - database.env
      - vars.env
    volumes:
      - './:/poupa-up'
    ports:
      - "7777:7777"
    environment:
      NODE_ENV: "testing"
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - database.env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database: #